Tomcat:
  port: 8099
  asyncTimeout: 60000

logging:
  level:
    org.springframework: INFO
    com.vijay.learn: TRACE


mongo:
  dbname:
  host: localhost
  port: 27017
  replicaHosts:
  user:
  password:
  useReplicas: false
  connectionsPerHost: 120
  threadsAllowedToBlock: 2
  connectTimeout: 1000
  maxWaitTime: 1900
  socketKeepAlive: true
  replicaSetName: demo
  useScram: false

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/dasboot
    username: vijay
    password: vijay
    driver-class-name: org.h2.Driver
    #common pooling configuration
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1

  jpa:
    hibernate:
      ddl-auto: false

flyway:
  baseline-on-migrate: true
  locations: classpath:Repository/migration

datasource:
  flyway:
    url: jdbc:h2:file:~/dasboot
    username: vijay
    password: vijay
    driver-class-name: org.h2.Driver
#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: springboot
#    password: springboot1
#    driver-class-name: oracle.jdbc.OracleDriver




